import { Router } from 'express';
import * as noteController from '../controllers/note.controller.js';
import { validate } from '../middlewares/validate.js';
import * as noteValidator from '../validators/note.validator.js';
import { aiLimiter } from '../middlewares/rateLimit.js';
import { authorize } from '../middlewares/authorize.js';
import { Permissions } from '../constants/permissions.js';

const router = Router();

/**
 * @openapi
 * /api/notes/generate:
 *   post:
 *     tags: [Notes]
 *     summary: Generate an AI clinical note from raw doctor input
 *     description: >
 *       Accepts free-form clinical text and returns a structured SOAP/clinical note
 *       generated by the AI model. Rate limited to prevent abuse.
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/GenerateNoteInput'
 *     responses:
 *       201:
 *         description: Note generated and saved successfully
 *         content:
 *           application/json:
 *             schema:
 *               allOf:
 *                 - $ref: '#/components/schemas/SuccessEnvelope'
 *                 - type: object
 *                   properties:
 *                     data:
 *                       type: object
 *                       properties:
 *                         id:
 *                           type: string
 *                           format: uuid
 *                         structuredOutput:
 *                           type: object
 *                           description: AI-generated structured clinical note
 *       400:
 *         description: Validation error
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/ErrorEnvelope'
 *       401:
 *         description: Unauthorized
 *       429:
 *         description: AI rate limit exceeded
 */
router.post(
  '/generate',
  authorize(Permissions.NOTE_CREATE),
  aiLimiter,
  validate(noteValidator.generateNoteSchema),
  noteController.generate
);

/**
 * @openapi
 * /api/notes:
 *   get:
 *     tags: [Notes]
 *     summary: List notes for the authenticated doctor
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: query
 *         name: page
 *         schema:
 *           type: integer
 *           minimum: 1
 *           default: 1
 *         description: Page number
 *       - in: query
 *         name: limit
 *         schema:
 *           type: integer
 *           minimum: 1
 *           maximum: 100
 *           default: 10
 *         description: Results per page
 *       - in: query
 *         name: patientId
 *         schema:
 *           type: string
 *           format: uuid
 *         description: Filter notes by patient ID (optional)
 *     responses:
 *       200:
 *         description: Paginated list of notes
 *         content:
 *           application/json:
 *             schema:
 *               allOf:
 *                 - $ref: '#/components/schemas/SuccessEnvelope'
 *                 - type: object
 *                   properties:
 *                     data:
 *                       $ref: '#/components/schemas/PaginatedNotes'
 *       401:
 *         description: Unauthorized
 */
router.get(
  '/',
  authorize(Permissions.NOTE_READ),
  validate(noteValidator.listNotesSchema),
  noteController.list
);

/**
 * @openapi
 * /api/notes/{id}:
 *   get:
 *     tags: [Notes]
 *     summary: Get a single note by ID
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *           format: uuid
 *         description: Note UUID
 *     responses:
 *       200:
 *         description: Note found
 *         content:
 *           application/json:
 *             schema:
 *               allOf:
 *                 - $ref: '#/components/schemas/SuccessEnvelope'
 *                 - type: object
 *                   properties:
 *                     data:
 *                       $ref: '#/components/schemas/Note'
 *       401:
 *         description: Unauthorized
 *       404:
 *         description: Note not found
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/ErrorEnvelope'
 */
router.get(
  '/:id',
  authorize(Permissions.NOTE_READ),
  validate(noteValidator.noteIdSchema),
  noteController.getById
);

/**
 * @openapi
 * /api/notes/{id}/pdf:
 *   get:
 *     tags: [Notes]
 *     summary: Download a note as a PDF file
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *           format: uuid
 *         description: Note UUID
 *     responses:
 *       200:
 *         description: PDF file stream
 *         content:
 *           application/pdf:
 *             schema:
 *               type: string
 *               format: binary
 *       401:
 *         description: Unauthorized
 *       404:
 *         description: Note not found
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/ErrorEnvelope'
 */
router.get(
  '/:id/pdf',
  authorize(Permissions.NOTE_READ),
  validate(noteValidator.noteIdSchema),
  noteController.pdf
);

export default router;
