export const AuditAction = Object.freeze({
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  PATIENT_CREATED: 'PATIENT_CREATED',
  PATIENT_UPDATED: 'PATIENT_UPDATED',
  PATIENT_DELETED: 'PATIENT_DELETED',
  NOTE_CREATED: 'NOTE_CREATED',
  NOTE_UPDATED: 'NOTE_UPDATED',
  NOTE_DELETED: 'NOTE_DELETED',
  USER_ROLE_CHANGED: 'USER_ROLE_CHANGED'
});

export const AuditEntityType = Object.freeze({
  USER: 'USER',
  PATIENT: 'PATIENT',
  NOTE: 'NOTE',
  VOICE_NOTE: 'VOICE_NOTE',
  REPORT: 'REPORT',
  AUTH: 'AUTH'
});
