export const Permissions = Object.freeze({
  PATIENT_CREATE: 'PATIENT_CREATE',
  PATIENT_READ: 'PATIENT_READ',
  PATIENT_UPDATE: 'PATIENT_UPDATE',
  PATIENT_DELETE: 'PATIENT_DELETE',
  NOTE_CREATE: 'NOTE_CREATE',
  NOTE_READ: 'NOTE_READ',
  NOTE_UPDATE: 'NOTE_UPDATE',
  NOTE_DELETE: 'NOTE_DELETE',
  TEMPLATE_CREATE: 'TEMPLATE_CREATE',
  TEMPLATE_READ: 'TEMPLATE_READ',
  TEMPLATE_UPDATE: 'TEMPLATE_UPDATE',
  TEMPLATE_DELETE: 'TEMPLATE_DELETE',
  USER_INVITE: 'USER_INVITE',
  USER_DELETE: 'USER_DELETE',
  AUDIT_VIEW: 'AUDIT_VIEW',
  BILLING_MANAGE: 'BILLING_MANAGE'
});

export const PERMISSION_VALUES = Object.freeze(Object.values(Permissions));
